apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-career-service
  labels:
    app: career-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: career-service
