apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth-service
  labels:
    app: auth-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: ENVIRONMENT
              value: {{ .Values.env.ENVIRONMENT | quote }}
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: {{ .Values.env.ACCESS_TOKEN_EXPIRE_MINUTES | quote }}
            - name: REFRESH_TOKEN_EXPIRE_DAYS
              value: {{ .Values.env.REFRESH_TOKEN_EXPIRE_DAYS | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: database-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: jwt-secret
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: jwt-refresh-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
